### ISSUE TITLE
Crash when open

### ISSUE THREAD

**Issue by Rawnly** [kaktus/kaktus#12]
I like the app design but...

![ezgif com-optimize](https://cloud.githubusercontent.com/assets/16429579/21741736/bcc5fa0e-d4df-11e6-8eb3-62a9b6b8345f.gif)

**MacOs Sierra**: `10.12.2`

**Comment by azer** [comment]
Sorry about it, I'm working on a version with more attention on the performance. It'll take some time though, because lately I'm actively traveling.

**Comment by mehmetkose** [comment]
+1
same issue here
sierra 10.12.3

**Comment by azer** [comment]
This is a general performance issue with the current version. My plan is to rewrite the whole thing from scratch without using any framework. You can track the progress at https://github.com/kaktus/kaktus/issues/14
