### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by Cwoodall6** [kaktus/kaktus#15]
![kaktus_logo-100](https://cloud.githubusercontent.com/assets/8728281/25440811/884644ac-2a6e-11e7-95b4-b4c0d2fbcb1a.jpg)

**Comment by azer** [comment]
thanks @Cwoodall6. I've actually worked on some logos but haven't had chance to update Kaktüs since I'm currently actively working on Kozmos (getkozmos.com). Kaktüs logo will also be similar to Kozmos. Thank you for the work though!

**Comment by Cwoodall6** [comment]
Aw man, keep up the good work!
