### ISSUE TITLE
build doesn't work

### ISSUE THREAD

**Issue by zeke** [kaktus/kaktus#3]
OS: MacOS 10.11.6
Kaktus: [1.0.0](https://github.com/kaktus/kaktus/releases/tag/1.0.0)

When I type in a URL and hit Enter, the input is cleared and nothing happens. I tried opening the web inspector to look for errors in the console, but the inspector won't open. 🤔

**Comment by azer** [comment]
I changed the URL with an earlier build, could you try that one ? https://cldup.com/a34ZFYO_rI.zip

**Comment by zeke** [comment]
Works!
